GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  title: "Заголовок блога",
  author: "Автор блога",
  url: "https://example.com",
  likes: 10
}