GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjUxZTkyNGJiNmVjZjZhYmYwODZjMGNjIiwiaWF0IjoxNjk3MDI0NDkwfQ.fFoSypr2SpQeDA52ST-gXGViongMo9O-LvVBDF3oTOs

# {
#   "title": "Заголовок блога22",
#   "author": "Автор блога22",
#   "url": "https://example222.com",
#   "likes": 1011
# }
{
  "title": "Совершенно новый",
  "author": "added a new blog",
  "url": "https://added_a_new_blog.com",
  "userId": "651e924bb6ecf6abf086c0cc"
}
