GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Заголовок блога22",
  "author": "Автор блога22",
  "url": "https://example222.com",
  "likes": 1011
}
