GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjUxZTkyNGJiNmVjZjZhYmYwODZjMGNjIiwiaWF0IjoxNjk3MDIzNzA4fQ.bl9IuX-s3xRsUWRJLy3dArvlVhsculljl0Us7kOfnZ4

# {
#   "title": "Заголовок блога22",
#   "author": "Автор блога22",
#   "url": "https://example222.com",
#   "likes": 1011
# }
{
  "title": "проверяем работу",
  "author": "Снова Света",
  "url": "https://example333.com",
  "userId": "651e924bb6ecf6abf086c0cc"
}
